### ISSUE TITLE
(Arsenal) game always freeze

### ISSUE THREAD

**Issue by mcletshacks** [Cesare0328/RVS#2]
is there any fix for that?

**Comment by Cesare0328** [comment]
this is fixed for version [1.3](https://github.com/Cesare0328/RVS/releases/tag/1.3) now

**Comment by ajiajijiajiaj** [comment]
> this is fixed for version [1.3](https://github.com/Cesare0328/RVS/releases/tag/1.3) now

my roblox still wont join a game its always freeze when joining a big games any fix of that? if i didnt attach/inject the executor it join faster if i attached it its just freeze
